### ISSUE TITLE
過濾輸入字串

### ISSUE THREAD

**Issue by r888800009** [tigercosmos/vocabulary-titan#1]
輸入`../../`之類的文字可以跑到字典其他的路徑，建議做個過濾會比較安全。
比方說`../../../zht/dictionary/english/hi`依然可以查到hi這個單字的解釋。

**Comment by r888800009** [comment]
因為主要是用來查詢單字，所以可以拿正規式判斷輸入的數值是不是英文字母或空白。

**Comment by tigercosmos** [comment]
yeah. It would be safe if there is a check for it. I will fix it later, or you might want to give a try. :)

**Comment by tigercosmos** [comment]
fixed
